### ISSUE TITLE
Error while import module

### ISSUE THREAD

**Issue by ejalaa12** [LionelDarras/PySimpleBGC#1]
Hello, 
I just downloaded your module. But when I tried to import it, I have the following error:

``` python
>>> import pysimplebgc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysimplebgc/__init__.py", line 13, in <module>
    from .logger import LOGGER, active_logger
  File "pysimplebgc/logger.py", line 14, in <module>
    from .compat import NullHandler
ImportError: cannot import name NullHandler

```

I'm using **python 2.7.6**.

Thank you for your help.

**Comment by ejalaa12** [comment]
I was able to make it work by changing the **compat.py** module so that it also import NullHandler if we are using python 2.x
